import './globals.css'
import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import Header from './components/Header'
import Sidebar from './components/Sidebar'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className='flex flex-col min-h-screen'>
        <Header />
        <div className='flex flex-1'>
          <Sidebar />
          {/* <div style={{ flex: 1, overflowY: 'scroll', paddingTop: '4rem', paddingLeft: '1rem' }}> */}
          <div className='flex-1 overflow-y-scroll pt-14 pl-4 max-h-screen'>
            {children}
          </div>
        </div>
      </body>
    </html>
  )
}
